config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'my_projects', to: 'projects#my_projects'

  get 'my_organizations', to: 'organizations#my_organizations'

  post 'interested', to: 'projects#interest'
  delete 'uninterested', to: 'projects#uninterest'

  resources :users
  resources :projects
  resources :events
  resources :organizations
end

app/views/pages/dashboard.html.erb
<% if @latest_projects.count != 0 %>
  <div class="container-fluid">
    <h1 align="center" class="sub-title">Latest Projects</h1>
    <div class="flex-between">
      <% @latest_projects.each do |t| %>
              <div class="card proj">
                <div class="avatar">
                    <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                </div>
                  <div class="content">
                      <p class="searchable">
                        <strong><%= t.title %></strong> <br>
                        Created by: <%= t.user.name %></p>
                      <%= link_to "Details", project_path(t), class: "btn btn-default" %>
                  </div>
              </div>
        <% end %>
    </div>
  </div>
<% end %>


<% if @latest_events.count != 0 %>
  <div class="container-fluid">
    <h1 align="center" class="sub-title">Latest Events</h1>
    <div class="flex-between">
      <% @latest_events.each do |t| %>
              <div class="card event">
                <div class="avatar">
                    <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                </div>
                  <div class="content">
                      <p class="searchable">
                        <strong><%= t.title %></strong> <br>
                      <%= link_to "Details", event_path(t), class: "btn btn-default" %>
                  </div>
              </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/pages/homepage.html.erb
<section id="home">
<%= image_tag("ist-collab-logo.png", alt: "Logo-ISTCollab", class: "img-responsive home-logo") %>
<div class="type-container">
  <span class="type-elem"></span>
</div>
  <div class="home-panel">
    <div class="row">
          <div class="col-md-6 col-sm-12">
            <%= link_to "Log In", login_path(), class: "btn btn-primary btn-lg home-button-LogIn btn-block"  %>
          </div>
          <div class="col-md-6  col-sm-12">
            <%= link_to "Sign Up", new_user_path(), class: "btn btn-success btn-lg home-button-SignUP btn-block" %>
          </div>
      </div>
  </div>
</section>
<script>
  $(function(){
      $(".type-elem").typed({
        strings: ["Create extra curricular projects.",
                  "Have an Idea for a project? Just create one project? And choose your collaborators!",
                  "Keep track of your favorite organizations workshops and competitions.",
                  "Extend your network and learn new things."],
        typeSpeed: 0,
        loop: true,
        showCursor: false,
        backDelay: 500,
      });
  });
</script>