config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'my_projects', to: 'projects#my_projects'

  get 'my_organizations', to: 'organizations#my_organizations'

  post 'interested', to: 'projects#interest'
  delete 'uninterested', to: 'projects#uninterest'

  resources :users
  resources :projects
  resources :events
  resources :organizations
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :categories

  validates :title, presence: true,
                    uniqueness: { case_sensitive: false }

  validates :description, presence: true,
                   length: { maximum: 500 }

  validates :category, presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100<" },
                             default_url: ":style/project.jpg"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :current_user
  def new
    @project = Project.new()
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to dashboard_path()
    else
      render 'new'
    end
  end

  def index
    @projects = Project.all()
  end

  def edit
    set_project
  end

  def show
    set_project
    @interests = @project.interests
    if @interests
      @interests = @interests.split(',')
      @people = []
      @interests.each do |user|
        @people << User.find(user.to_i)
      end
    end
    session[:project_id] = @project.id
  end

  def my_projects
    current_user
    @myProjects = @current_user.projects
  end

  def interest
    project = Project.find(session[:project_id])
    unless project.interests
      project.interests = @current_user.id.to_s
    else

      project.interests += ',' + @current_user.id.to_s
    end

    project.save
    redirect_to project_path(project)
  end

  def uninterest
    project = Project.find(session[:project_id])
    interests = project.interests
    interests = interests.split(',')
    interests = interests.map(&:to_i)
    interests.delete(current_user.id)
    interests = interests.map(&:to_s)
    interests = interests.join(',')
    project.interests = interests
    project.interests = nil unless project.interests.length > 0
    project.save
    redirect_to project_path(project)
  end

  def destroy
    project = Project.find(set_project)
    project.destroy
    redirect_to projects_path()
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :skills, :category, :avatar)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/views/projects/index.html.erb
<div class="container-fluid">
  <h1 align="center" class="sub-title">Projects</h1>
  <div align="center">
    <div class="inner-addon left-addon search-box">
      <i class="glyphicon glyphicon-search"></i>
      <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block" >
    </div>
  </div>
  <div class="flex-between">
    <% @projects.each do |t| %>
            <div class="card proj">
                <div class="avatar">
                    <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                </div>
                <div class="content">
                    <p class="searchable">
                      <strong><%= t.title %></strong> <br>
                      Created by: <%= t.user.name %></p>
                    <%= link_to "Details", project_path(t), class: "btn btn-default" %>
                </div>
            </div>
      <% end %>
  </div>
</div>

app/views/projects/my_projects.html.erb
<div class="container-fluid">
  <h1 align="center" class="sub-title">My Projects</h1>
  <div align="center">
    <div class="inner-addon left-addon search-box">
    <i class="glyphicon glyphicon-search"></i>
    <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block" >
    </div>
  </div>
  <div class="flex-between">
    <% @myProjects.each do |t| %>
            <div class="card proj">
              <div class="avatar">
                  <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
              </div>
                <div class="content">
                    <p class="searchable">
                      <strong><%= t.title %></strong> <br>
                      Created by: <%= t.user.name %></p>
                    <%= link_to "Details", project_path(t), class: "btn btn-default" %>
                </div>
            </div>
      <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= render "shared/errors", obj: @project %>
<div align="center" class="container container-max form">


  <h1 class="new-title-project">New Project</h1>

  <%= form_for @project do |t| %>
    <div class="form-group">
      <p>Title:</p>
      <%= t.text_field :title , placeholder: "Project X" , class: "form-control" %>
    </div>
    <div class="form-group">
      <p>Description:</p>
      <%= t.text_area :description , rows:"4" , placeholder: "This project makes someones life easier!" , class: "form-control" %>
    </div>
    <div class="form-group">
      <p>Category:</p>
      <%= t.text_field :category , placeholder: "Web Development, Mobile Development ..." , class: "form-control", id: "category" %>
    </div>
    <div class="form-group">
      <p>Skills:</p>
      <%= t.text_field :skills , placeholder: "Android, Ruby On Rails" , class: "form-control", id: "skills" %>
    </div>
    <div class="form-group">
      <%= t.file_field :avatar %>
    </div>
    <div class="form-group">
      <%= t.submit "Create Project" , class: "btn btn-primary new-buttom-project" %>
    </div>
  <% end %>

</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#skills').tokenfield()
    $('#category').tokenfield()
  });
</script>

app/views/projects/show.html.erb
<div class="container-fluid">
<div class="container">
	<div class="row">
		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile proj">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2> <%=@project.title%></h2>
                    <p><strong>Created by: </strong><%= link_to @project.user.name, user_path(@project.user) %></p>
                    <p><strong>Categories:</strong> <%=@project.category%></p>
                    <p><strong>Skills:</strong> <%=@project.skills%></p>
                    <p><strong>Description:</strong> <%=@project.description%></p>
                </div>
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                          <%= image_tag @project.avatar.url(:thumb), class: "img-md image-responsive " %>
                    </figure>
                </div>
                </div>
                <div class="col-xs-12 divider">
                <div class="col-xs-12 col-sm-4">
                    <h3><strong>Contacts</strong></h3>
                    <p><strong>Email: </strong><%=@project.user.email%></p>
										<p><strong>Telephone: </strong><%=@project.user.phone_number%></p>

                      <% if @current_user.id == @project.user.id  %>
                <% end %>

                </div>
            </div>
            <% if @current_user.id != @project.user.id  %>

              <% if @interests %>
              <div class="row">
                <div class="col-xs-2 center-block col-xs-offset-4">

              <% if @interests.include?(@current_user.id.to_s) %>

                <%= link_to "Not Interested" , uninterested_path(), method: :delete, class: "btn-default btn btn-danger" %>
								<% else %>
	                  <%= link_to "Show Interest" , interested_path(), method: :post, class: "btn-default btn btn-success" %>
	              <% end %>
              <% else %>
                  <%= link_to "Show Interest" , interested_path(), method: :post, class: "btn-default btn btn-success" %>
              <% end %>
            </div>
            </div>
            </div>
            <% else %>
          </div>
          <div class="container-fluid">
              <% if @people %>
              <h2>Interested collabers:</h2>
              <div class="row flex-between">
                  <% @people.each do |t| %>
                      <div class="card">
                          <div class="avatar">
                              <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                          </div>
                          <div class="content">
                              <%= link_to t.name , user_path(t), class: "btn btn-default" %>
                          </div>
                      </div>
                    <% end %>
              </div>
              <% end %>
		             <div class="row" style="margin-bottom: 20px">
		               <div align="center" class="center-block col-xs-offset-4">
		                 <%= link_to "Close Project", project_path(@project), method: "delete", class: "btn btn-default btn-danger btn-primary " %>
		             </div>
		             </div>
          <% end %>
    	 </div>
		</div>
	</div>
</div>