config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'my_projects', to: 'projects#my_projects'

  get 'my_organizations', to: 'organizations#my_organizations'

  post 'interested', to: 'projects#interest'
  delete 'uninterested', to: 'projects#uninterest'

  resources :users
  resources :projects
  resources :events
  resources :organizations
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :events
  belongs_to :user
  
  validates :title, presence: true, uniqueness: true,
                   length: { maximum: 50 }

  validates :description, length: { maximum: 500 }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100<" },
                             default_url: ":style/default-avatar.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :current_user

  def new
    @organization = Organization.new()
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.user = @current_user
    if @organization.save
      redirect_to my_organizations_path()
    else
      render 'new'
    end
  end

  def index
    @organizations = Organization.all()
  end

  def edit
    set_organization
  end

  def update
    set_organization
#     require_same_user
    if @organization.update(organization_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    set_organization
    session[:organization_id] = @organization.id
  end

  def my_organizations
    current_user
    @myOrganizations = @current_user.organizations
  end

  private
  def organization_params
    params.require(:organization).permit(:title, :description, :interests, :skills, :avatar)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

#   def require_same_organization
#     if current_user != @user && !current_user.admin?
#       flash[:danger] = "You can only edit your own accout"
#       redirect_to root_path
#     end
#   end

end

app/views/organizations/index.html.erb
<div class="container-fluid">
  <h1 align="center" class="sub-title">Organizations</h1>
  <div align="center">
    <div class="inner-addon left-addon search-box">
      <i class="glyphicon glyphicon-search"></i>
      <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block">
    </div>
  </div>
  <div class="flex-between">
    <% @organizations.each do |t| %>
        <div class="card org">
          <div class="avatar">
            <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
          </div>
          <div class="content">
            <p class="searchable">
              <strong><%= t.title %></strong> <br>
              <%= t.description %></p>
            <%= link_to "Profile", organization_path(t), class: "btn btn-default" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/organizations/my_organizations.html.erb
<div class="container-fluid">
  <h1 align="center" class="sub-title">My Organizations</h1>
  <div align="center">
    <div class="inner-addon left-addon search-box">
    <i class="glyphicon glyphicon-search"></i>
    <input type="text" id="search" placeholder="Search" autocomplete="off" class="form-control center-block" >
    </div>
  </div>
  <div class="flex-between">
    <% @myOrganizations.each do |t| %>
            <div class="card org">
                <div class="avatar">
                    <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                </div>
                <div class="content">
                    <p class="searchable">
                      <strong><%= t.title %></strong> <br>
                      <%= t.description %></p>
                    <%= link_to "Profile", organization_path(t), class: "btn btn-default" %>
                </div>
            </div>
      <% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<section id="new-profile">
  <div align="center" class="container-max container form">

    <h1 class="new-title-sign-up">New Organization</h1>

    <%= form_for @organization, html: { multipart: true } do |t| %>

      <div class="form-group">
        <p>Name:</p>
        <%= t.text_field :title , placeholder: "NEETI" , class: "form-control" %>
      </div>

      <div class="form-group">
        <p>Description:</p>
        <%= t.text_area :description , rows: "4" , placeholder: "Nucleo de estudantes do curso de engenharia de Telecomunicações e Informática" , class: "form-control" %>
      </div>

      <div class="form-group">
        <%= t.file_field :avatar %>
      </div>

      <div class="form-group">
        <%= t.submit "Create Organization" , class: "btn btn-primary new-buttom-project" %>
      </div>
    <% end %>

    <%= render "shared/errors", obj: @organization %>
  </div>
</section>

app/views/organizations/show.html.erb
<div class="container-fluid">
<div class="container">
	<div class="row">
		<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile org">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2> <%=@organization.title%></h2>

                    <p><strong>Admin: </strong><%= link_to @organization.user.name, user_path(@organization.user) %></p>

                    <p><strong>Description: </strong> <%=@organization.description%></p>

                </div>
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                          <%= image_tag @organization.avatar.url(:thumb), class: "img-md image-responsive " %>
                    </figure>
                </div>
                </div>
                <div class="col-xs-12 divider">
                <div class="col-xs-12 col-sm-4">
                    <h3><strong>Contacts</strong></h3>
                    <p><strong>Email: </strong><%=@organization .user.email%></p>
										<p><strong>Phone Number: </strong><%=@organization .user.phone_number%></p>

                      <% if @current_user.id == @organization .user.id  %>
                <% end %>

                </div>
            </div>
						<% if @current_user.id == @organization.user.id  %>
             <div class="row">
               <div align="center" class="center-block col-xs-offset-4">
                 <%= link_to "New Event", new_event_path(), class: "btn btn-default btn btn-primary " %>
             </div>
             </div>
				 <% end %>
    	 </div>
		</div>
	</div>
</div>

<!--  Events from the Organization -->
  
  <h1 align="center" class="sub-sub-title">Events</h1>
  <div class="row flex-between">
      <% @organization.events.each do |t| %>
              <div class="card event">
                  <div class="avatar">
                      <%= image_tag t.avatar.url(:thumb), class: "image-responsive" %>
                  </div>
                  <div class="content">
                      <p class="searchable">
                        <%= t.title %> <br>
                        <%= t.description %>
                        <%= t.category %>
                      </p>
                      <p>

                        <%= link_to "Details", event_path(t), class: "btn btn-default btn btn-primary " %>
                  </div>
              </div>
        <% end %>
  </div>
</div>

<script type="text/javascript">

  $(document).ready(function() {

    var timeoutID = null;

    function findMember(str) {
      $('.users-list li').each(function(){
        var text = $(this).text()

        if(text.search(str) < 0)
          $(this).fadeOut();
          else
          $(this).fadeIn();

      });
    }

    $('#search').keyup(function(e) {
      clearTimeout(timeoutID);
      timeoutID = setTimeout(findMember.bind(undefined, e.target.value), 500);
    });

  });
</script>