config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'my_projects', to: 'projects#my_projects'

  get 'my_organizations', to: 'organizations#my_organizations'

  post 'interested', to: 'projects#interest'
  delete 'uninterested', to: 'projects#uninterest'

  resources :users
  resources :projects
  resources :events
  resources :organizations
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default header">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand navbar-logo" href="<%= root_path()%>"><%= image_tag("ist-collab-logo.png", alt: "IST Collab", class: "img-responsive") %></a>
  </div>
  <div class="navbar-collapse collapse">
    <%= image_tag @current_user.avatar.url(:thumb), class: "image-responsive user-logo" %>


    <span class="user-name"><%= link_to @current_user.name, edit_user_path(@current_user) %></span>
    <ul class="nav navbar-nav nav-links">
      <li> <%= link_to "Events", events_path()  %></li>
      <li> <%= link_to "Users", users_path()  %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Organizations <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "New Organization", new_organization_path()%></li>
          <li><%= link_to "My Organizations", my_organizations_path()%></li>
          <li><%= link_to "Show All Organizations", organizations_path()%></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Projects <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "New Project", new_project_path()%></li>
          <li><%= link_to "My Projects", my_projects_path()%></li>
          <li><%= link_to "Show All Projects", projects_path()%></li>
        </ul>
      </li>
      <li> <%= link_to "Log Out", logout_path(), method: "delete" %></li>
    </ul>
</div>
</nav>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IST Collab</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" if logged_in? %>
    <%= render "layouts/messages" %>
      <%= yield %>
  </body>
</html>